name: "✨ Feature Request"
description: "Suggest a new feature or enhancement for this project."
title: "[Feature Request]: "
labels: ["Feature", "Needs Triage"]
body:
  - type: textarea
    id: "feature_description"
    attributes:
      label: "Feature Description"
      description: "Provide a clear and detailed description of the feature you'd like to see implemented. Include any relevant context or use cases."
    validations:
      required: true

  - type: textarea
    id: "feature_screenshots"
    attributes:
      label: "Screenshots (if applicable)"
      description: "Attach relevant screenshots or mockups to help explain your feature request."
    validations:
      required: false
